name: Feature Request
description: Suggest an idea for this module.
title: "[Feature]: "
labels:
  - enhancement
assignees:
  - claudiospizzi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature. Please note, this is a spare time community open source project and there is no obligation that the feature will be implemented.
  - type: textarea
    id: feature
    attributes:
      label: Feature Specification
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Provide a clear and concise description of what the problem is. For example, "I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives
      description: Let us know about other solutions you've tried or researched.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.
    validations:
      required: false
